language: python
node_js:
  - "2.7"
install:
  - make install
script:
  - . venv/bin/activate && gulp build --root /campl-ng
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN